name: pybreaks
channels:
  - conda-forge
  - defaults
dependencies:
- setuptools
- numpy
- netCDF4
- scipy
- pandas
- pyproj # for pytesmo
- pip
- pip:
  - datetime
  - scikit-learn
  - statsmodels
  - matplotlib
  - seaborn
  - smecv_grid
  - pytesmo
  - git+git://github.com/OpenHydrology/lmoments3.git@develop
