name: pybreaks
channels:
  - conda-forge
  - defaults
dependencies:
- setuptools
- numpy<2.0
- netCDF4
- scipy
- pandas
- pyproj
- pykdtree
- pip
- pip:
  - datetime
  - scikit-learn
  - statsmodels
  - matplotlib
  - seaborn
  - smecv_grid
  - pytesmo
  - more_itertools
  - lmoments3
  - pytest
  - pytest-cov
