name: pybreaks
channels:
  - conda-forge
dependencies:
- setuptools
- numpy
- netCDF4
- scipy
- pandas
#- typing
#- toolz
#- cartopy
- pip:
#  - multiprocessing
  - datetime
#  - smecv_grid
  - scikit-learn
#  - rsdata
#  - rsroot
#  - pynetcf
#  - pygeogrids
#  - parse
#  - pyyaml
  - statsmodels
  - git+https://github.com/OpenHydrology/lmoments3@develop
  - matplotlib
  - seaborn
#  - xarray
  - pytesmo


