name: pybreaks
channels:
  - conda-forge
  - defaults
dependencies:
- setuptools
- numpy
- netCDF4
- scipy
- pandas
- pyproj
- pykdtree
- pip
- pip:
  - datetime
  - scikit-learn
  - statsmodels
  - matplotlib
  - seaborn
  - smecv_grid
  - pytesmo
  - more_itertools
  - git+https://github.com/wpreimes/lmoments3@develop
  - pytest
  - pytest-cov
